Update makepkg

diff --git a/makepkg b/makepkg
--- a/makepkg
+++ b/makepkg
@@ -352,11 +352,12 @@ remove_deps() {
 
 error_function() {
 	# first exit all subshells, then print the error
-	if (( ! BASH_SUBSHELL )); then
-		error "$(gettext "A failure occurred in %s().")" "$1"
-		plain "$(gettext "Aborting...")"
-	fi
-	exit $E_USER_FUNCTION_FAILED
+	#if (( ! BASH_SUBSHELL )); then
+	#	error "$(gettext "A failure occurred in %s().")" "$1"
+	#	plain "$(gettext "Aborting...")"
+	#fi
+	#exit $E_USER_FUNCTION_FAILED
+	echo print the error MOD2
 }
 
 merge_arch_attrs() {
